# Generated by Django 3.1.4 on 2020-12-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201223_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('Cheminformatics', 'Cheminformatics'), ('Bioinformatics', 'Bioinformatics'), ('CompChem', 'CompChem'), ('CompBio', 'CompBio')], default='Cheminformatics', max_length=25),
        ),
    ]
