# Generated by Django 3.1.4 on 2020-12-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201225_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('Cheminformatics', 'Cheminformatics'), ('Bioinformatics', 'Bioinformatics'), ('Computational Chemistry', 'Computational Chemistry'), ('Computational Biology', 'Computational Biology'), ('Tutorials', 'Tutorials')], default='Cheminformatics', max_length=25),
        ),
    ]
