# Generated by Django 3.1.4 on 2020-12-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201225_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('Cheminformatics', 'Cheminformatics'), ('Bioinformatics', 'Bioinformatics'), ('CompChem', 'CompChem'), ('CompBio', 'CompBio'), ('Tutorials', 'Tutorials')], default='Cheminformatics', max_length=25),
        ),
    ]
